-- 059: Remap Clerk user IDs from the dev instance (sweet-lionfish-23) to the
-- production instance. Generated by scripts/migrate-clerk-to-prod.mjs.
-- NOT destructive (pure ID rewrite); re-runnable — rows already remapped no
-- longer match old_id. Run during the cutover window, right before the Vercel
-- key swap. No TEMP table / explicit transaction — the Supabase SQL editor
-- doesn't carry those across statements; the helper table is real and dropped
-- in a follow-up statement AFTER the verification counts read all zeros.

CREATE TABLE IF NOT EXISTS _clerk_id_map_059 (old_id TEXT PRIMARY KEY, new_id TEXT NOT NULL UNIQUE);
INSERT INTO _clerk_id_map_059 (old_id, new_id) VALUES
  ('user_3FratqGwYHnV6bBpX5WYkgJsAEf', 'user_3FzFNN1y3Xm7UfVNbbZtouKsLuo'),
  ('user_3FpCVrQuKnIYdotZOhpCoMz1YrD', 'user_3FzFNJa1BGesgZx2oiEzpxnJZ5v'),
  ('user_3FnCCbN14XtRZSMl1cLJpHMnerj', 'user_3FzFNW95SsxDYLTbzN4T85STMlc'),
  ('user_3FYKfNYG5PdxC9xQ4J20lUuGMh6', 'user_3FzFNVjs8z9HgQiBwVt4Re1snlI'),
  ('user_3FY18VkPfgMFRXS5zdTEXAyYTNG', 'user_3FzFNRDe3GId5wOQNALl6NvcmH0'),
  ('user_3FWffEveTqOkb8tLjTcY9jOVH5h', 'user_3FzFNW6DZwJ2tYAT7dCevX6Uzfd'),
  ('user_3FWcGiJInHdl58O8YM7iToTkqi1', 'user_3FzFNQe9JhbmclHa1rtWCNmQgrF'),
  ('user_3FW44ZkFX5eSyPJCBHBtU5VbRGF', 'user_3FzFNWrtYoTnYGAgs9FxCyS6eJz'),
  ('user_3FVvSmkJ9uL0SeXmN4vD4337n6C', 'user_3FzFNcQUTeyrNcFD6MxIuJ6CL1D'),
  ('user_3EvkDMnAyS0tjkCvGD4Wv3qZwrx', 'user_3FzFNcHvUXWAxTJKxVWDYYhR7bT'),
  ('user_3Eg5T4XL8NA8dAmVzAIGzpoM4Tl', 'user_3FzFNbhaViOecrOl3LJUkGI2JGy'),
  ('user_3EYYQA0QQOhZnIbO4Huk8wDnHJp', 'user_3FzFNZZ3nAW5lr3lZ4FnoCxVuei'),
  ('user_3EWF4XCbn11O3Zes3WZTaKnS6QP', 'user_3FzFNeOPdCktyhV0GBz7jG65NUi'),
  ('user_3EW7u4Ukh30XvGmJnWcbS6qWOQm', 'user_3FzFNcKrSa23B29hreG33o8xppY'),
  ('user_3EW5zOfYWtv3A6H8YG08LYYBV0y', 'user_3FzFNfqs0hvm2W8IX9Lo95gMm5k'),
  ('user_3EVlFDVw0C4JM4ey4O7vDoJizIX', 'user_3FzFNi4NjterOtu6iXIzI33OPQ3'),
  ('user_3ESAH7geSjhxTqS7KQ6Bv33bgnP', 'user_3FzFNn0Jc79wZwJNBVukSPOKraL'),
  ('user_3ES6h9lXkhZlmnzUfDucDASzw36', 'user_3FzFNm48CTkSQahzzXzdIRfXg59'),
  ('user_3ENnm48yOj9nmfN8AoDh9spIhOT', 'user_3FzFNhaQsb27httEmHLlOTzBGU9'),
  ('user_3ENEneF1XBY0gcbZqAgrqYfjByz', 'user_3FzFNj64l6AnPUotW7kaAhaCG3b'),
  ('user_3Di8ANzyQBbtY0g2SOVE2ndVpEB', 'user_3FzFNtyarUmwtiTuaWqZVu6T2vd')
ON CONFLICT (old_id) DO NOTHING;

UPDATE applications SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE applications.clerk_user_id = m.old_id;
UPDATE members SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE members.clerk_user_id = m.old_id;
UPDATE volunteers SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE volunteers.clerk_user_id = m.old_id;
UPDATE camp_signups SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE camp_signups.clerk_user_id = m.old_id;
UPDATE group_members SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE group_members.clerk_user_id = m.old_id;
UPDATE member_shift_signups SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE member_shift_signups.clerk_user_id = m.old_id;
UPDATE user_notifications SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE user_notifications.clerk_user_id = m.old_id;
UPDATE conversation_participants SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE conversation_participants.clerk_user_id = m.old_id;
UPDATE shoutouts SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE shoutouts.clerk_user_id = m.old_id;
UPDATE role_suggestions SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE role_suggestions.clerk_user_id = m.old_id;
UPDATE attunement_nudges SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE attunement_nudges.clerk_user_id = m.old_id;
UPDATE lead_up_event_rsvps SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE lead_up_event_rsvps.clerk_user_id = m.old_id;
UPDATE resource_claims SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE resource_claims.clerk_user_id = m.old_id;
UPDATE poll_votes SET clerk_user_id = m.new_id FROM _clerk_id_map_059 m WHERE poll_votes.clerk_user_id = m.old_id;
UPDATE member_distinctions SET granted_by = m.new_id FROM _clerk_id_map_059 m WHERE member_distinctions.granted_by = m.old_id;
UPDATE messages SET sender_clerk_id = m.new_id FROM _clerk_id_map_059 m WHERE messages.sender_clerk_id = m.old_id;
UPDATE messages SET recipient_clerk_id = m.new_id FROM _clerk_id_map_059 m WHERE messages.recipient_clerk_id = m.old_id;
UPDATE resources SET offered_by = m.new_id FROM _clerk_id_map_059 m WHERE resources.offered_by = m.old_id;

-- conversations.direct_key = the two clerk ids sorted + '|'-joined; remap both
-- halves and re-sort. Unmapped halves (deleted users) pass through unchanged.
UPDATE conversations c SET direct_key = sub.new_key
FROM (
  SELECT c2.id,
         (SELECT string_agg(COALESCE(m.new_id, t.part), '|' ORDER BY COALESCE(m.new_id, t.part))
          FROM unnest(string_to_array(c2.direct_key, '|')) AS t(part)
          LEFT JOIN _clerk_id_map_059 m ON m.old_id = t.part) AS new_key
  FROM conversations c2
  WHERE c2.direct_key IS NOT NULL
) sub
WHERE c.id = sub.id AND c.direct_key IS DISTINCT FROM sub.new_key;

-- Verification (last statement, so the editor shows it): every row must be 0.
-- Once it is, run:  DROP TABLE _clerk_id_map_059;
SELECT 'applications.clerk_user_id' AS col, count(*) AS still_old FROM applications WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'members.clerk_user_id' AS col, count(*) AS still_old FROM members WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'volunteers.clerk_user_id' AS col, count(*) AS still_old FROM volunteers WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'camp_signups.clerk_user_id' AS col, count(*) AS still_old FROM camp_signups WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'group_members.clerk_user_id' AS col, count(*) AS still_old FROM group_members WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'member_shift_signups.clerk_user_id' AS col, count(*) AS still_old FROM member_shift_signups WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'user_notifications.clerk_user_id' AS col, count(*) AS still_old FROM user_notifications WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'conversation_participants.clerk_user_id' AS col, count(*) AS still_old FROM conversation_participants WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'shoutouts.clerk_user_id' AS col, count(*) AS still_old FROM shoutouts WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'role_suggestions.clerk_user_id' AS col, count(*) AS still_old FROM role_suggestions WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'attunement_nudges.clerk_user_id' AS col, count(*) AS still_old FROM attunement_nudges WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'lead_up_event_rsvps.clerk_user_id' AS col, count(*) AS still_old FROM lead_up_event_rsvps WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'resource_claims.clerk_user_id' AS col, count(*) AS still_old FROM resource_claims WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'poll_votes.clerk_user_id' AS col, count(*) AS still_old FROM poll_votes WHERE clerk_user_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'member_distinctions.granted_by' AS col, count(*) AS still_old FROM member_distinctions WHERE granted_by IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'messages.sender_clerk_id' AS col, count(*) AS still_old FROM messages WHERE sender_clerk_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'messages.recipient_clerk_id' AS col, count(*) AS still_old FROM messages WHERE recipient_clerk_id IN (SELECT old_id FROM _clerk_id_map_059)
UNION ALL
SELECT 'resources.offered_by' AS col, count(*) AS still_old FROM resources WHERE offered_by IN (SELECT old_id FROM _clerk_id_map_059);
